from .Tbl_Materias import Tbl_Materias
from .Tbl_Aula import Tbl_Aula
from .Tbl_Colegio import Tbl_MTbl_Colegio
from .Tbl_Coordinador import Tbl_Coordinador
from .Tbl_Docente import Tbl_Docente
from .Tbl_GradoMateria import Tbl_Tbl_GradoMateria
from .Tbl_Grupo import Tbl_Grupo
from .Tbl_Horario import Tbl_Horario
from .Tbl_HorarioDocente import Tbl_HorarioDocente
from .Tbl_Usuario import Tbl_Usuario
from .Tbl_Grado import Tbl_Grado
